#!/usr/bin/env python3
"""agent_notes.py - keeps the agent notes cheap to load and easy to find.

The notes a model needs to fix a bug in this repo live in docs/agents/*.md, one
file per topic, each note a "- **headline.** body" bullet that was measured
before it was written. AGENTS.md is the MAP: small enough to be loaded into
every session (CLAUDE.md imports it), it says which file to open for which
symptom.

    python agent_notes.py --index   regenerate docs/agents/INDEX.md (one line per
                                    note headline, grouped by file - grep it)
    python agent_notes.py           check: map under budget, every topic file
                                    referenced from the map, INDEX.md fresh,
                                    CLAUDE.md still a stub that imports the map

Budget: AGENTS.md <= 20 KB (~5k tokens). The old single CLAUDE.md was 141 KB -
~35k tokens paid by every model on every session.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
NOTES = ROOT / "docs" / "agents"
MAP = ROOT / "AGENTS.md"
BUDGET = 20 * 1024

files = sorted(p for p in NOTES.glob("*.md") if p.name != "INDEX.md")
map_text = MAP.read_text(encoding="utf-8")
m = re.search(r"^# (.+?) — ", map_text, re.M)
PRODUCT = m.group(1) if m else ROOT.name


def headlines(text):
    return [re.sub(r"\s+", " ", h).strip() for h in re.findall(r"^- \*\*([\s\S]*?)\*\*", text, re.M)]


def title(text):
    m = re.search(r"^# (.+)$", text, re.M)
    return m.group(1) if m else "?"


def build_index():
    out = [f"# Index of {PRODUCT}'s agent notes\n\nGenerated by `python agent_notes.py --index`; do not hand-edit. One line per note, grouped by file — grep this, then open the file.\n"]
    total = 0
    for p in files:
        text = p.read_text(encoding="utf-8")
        hs = headlines(text)
        if not hs:
            continue
        total += len(hs)
        out.append(f"\n## {title(text)} — `docs/agents/{p.name}` ({len(hs)})\n\n" + "\n".join("- " + h for h in hs) + "\n")
    return "".join(out), total


if len(sys.argv) > 1 and sys.argv[1] == "--index":
    out, total = build_index()
    (NOTES / "INDEX.md").write_text(out, encoding="utf-8")
    print(f"docs/agents/INDEX.md: {total} notes across {len(files)} files")
    sys.exit(0)

bad = 0


def check(cond, msg):
    global bad
    if cond:
        print("ok    " + msg)
    else:
        bad += 1
        print("FAIL  " + msg)


size = len(map_text.encode("utf-8"))
check(size <= BUDGET, f"AGENTS.md is {size} bytes (~{size // 4} tokens), under the {BUDGET // 1024} KB budget")
for p in files:
    check(f"docs/agents/{p.name}" in map_text, f"the map points at docs/agents/{p.name}")
out, _ = build_index()
current = (NOTES / "INDEX.md").read_text(encoding="utf-8").replace("\r\n", "\n") if (NOTES / "INDEX.md").exists() else ""
check(current == out, "docs/agents/INDEX.md is fresh (run `python agent_notes.py --index`)")
claude = (ROOT / "CLAUDE.md").read_text(encoding="utf-8").replace("\r\n", "\n")
check(re.search(r"^@AGENTS\.md$", claude, re.M) is not None, "CLAUDE.md imports AGENTS.md")
check(len(claude) < 2048, f"CLAUDE.md is {len(claude)} bytes — it should stay a stub that imports the map")
for p in files:
    check(f"> Part of {PRODUCT}'s agent notes" in p.read_text(encoding="utf-8"), f"docs/agents/{p.name} carries the pointer back to the map")
print("\n" + (f"{bad} problem(s)" if bad else "all good"))
sys.exit(1 if bad else 0)
